# permissions for end users to view dbmmoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbmmo-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmoes/status
  verbs:
  - get
