# permissions for end users to view dbmmomysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbmmomysql-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmomysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmomysqls/status
  verbs:
  - get
