# permissions for end users to edit dbmmoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbmmo-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmoes/status
  verbs:
  - get
