# permissions for end users to edit dbmmomysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbmmomysql-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmomysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - dbmmomysqls/status
  verbs:
  - get
