// +build !ignore_autogenerated

/*
Copyright 2020 HubertStefanski.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
	if in.AzureClientID != nil {
		in, out := &in.AzureClientID, &out.AzureClientID
		*out = new(string)
		**out = **in
	}
	if in.AzureClientSecret != nil {
		in, out := &in.AzureClientSecret, &out.AzureClientSecret
		*out = new(string)
		**out = **in
	}
	if in.AzureTenantID != nil {
		in, out := &in.AzureTenantID, &out.AzureTenantID
		*out = new(string)
		**out = **in
	}
	if in.AzureSubscriptionID != nil {
		in, out := &in.AzureSubscriptionID, &out.AzureSubscriptionID
		*out = new(string)
		**out = **in
	}
	if in.AzureBaseGroupName != nil {
		in, out := &in.AzureBaseGroupName, &out.AzureBaseGroupName
		*out = new(string)
		**out = **in
	}
	if in.AzureLocationDefault != nil {
		in, out := &in.AzureLocationDefault, &out.AzureLocationDefault
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMMOMYSQLDeployment) DeepCopyInto(out *DBMMOMYSQLDeployment) {
	*out = *in
	if in.DeploymentType != nil {
		in, out := &in.DeploymentType, &out.DeploymentType
		*out = new(string)
		**out = **in
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AzureConfig != nil {
		in, out := &in.AzureConfig, &out.AzureConfig
		*out = new(AzureConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMMOMYSQLDeployment.
func (in *DBMMOMYSQLDeployment) DeepCopy() *DBMMOMYSQLDeployment {
	if in == nil {
		return nil
	}
	out := new(DBMMOMYSQLDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMMOMySQL) DeepCopyInto(out *DBMMOMySQL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMMOMySQL.
func (in *DBMMOMySQL) DeepCopy() *DBMMOMySQL {
	if in == nil {
		return nil
	}
	out := new(DBMMOMySQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBMMOMySQL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMMOMySQLList) DeepCopyInto(out *DBMMOMySQLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBMMOMySQL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMMOMySQLList.
func (in *DBMMOMySQLList) DeepCopy() *DBMMOMySQLList {
	if in == nil {
		return nil
	}
	out := new(DBMMOMySQLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBMMOMySQLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMMOMySQLSpec) DeepCopyInto(out *DBMMOMySQLSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DBMMOMYSQLDeployment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMMOMySQLSpec.
func (in *DBMMOMySQLSpec) DeepCopy() *DBMMOMySQLSpec {
	if in == nil {
		return nil
	}
	out := new(DBMMOMySQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBMMOMySQLStatus) DeepCopyInto(out *DBMMOMySQLStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PersistentVolumeClaims != nil {
		in, out := &in.PersistentVolumeClaims, &out.PersistentVolumeClaims
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBMMOMySQLStatus.
func (in *DBMMOMySQLStatus) DeepCopy() *DBMMOMySQLStatus {
	if in == nil {
		return nil
	}
	out := new(DBMMOMySQLStatus)
	in.DeepCopyInto(out)
	return out
}
