---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dbmm-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: dbmm-operator
    namespace: __NAMESPACE__
roleRef:
  kind: ClusterRole
  name: dbmm-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
