---
apiVersion: cache.my.domain/v1alpha1
kind: DBMMOMySQL
metadata:
  name: dbmmo-mysql
  labels:
    type: example
spec:
  size: 1
  deployment:
    ingress:
      enabled: False
    deploymentType: "OnCluster"
    envFrom:
      - secretRef:
          name: dbmmo-mysql-secret