---
apiVersion: cache.my.domain/v1alpha1
kind: DBMMOMySQL
metadata:
  name: dbmmo-mysql
  labels:
    type: example
spec:
  size: 1
  deployment:
    ingress:
      enabled: False
    deploymentType: "OnCluster"
    initCMD: "CREATE TABLE IF NOT EXISTS tasks (
    task_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start_date DATE,
    due_date DATE,
    status TINYINT NOT NULL,
    priority TINYINT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;"
    envFrom:
      - secretRef:
          name: dbmmo-mysql-secret